export const articles = [
 {slug:'cargador-usb-c-portatiles',category:'Tecnología',type:'Claves',title:'Un mismo puerto, distintos cargadores: lo que cambia con el USB-C',summary:'El cargador común ya alcanza a los portátiles. Antes de reutilizar el del móvil, conviene mirar algo más que la forma del conector.',minutes:4,lead:true,sections:[['Qué ha cambiado','El calendario del cargador común de la Unión Europea incluyó los portátiles desde el 28 de abril de 2026. La medida busca reducir la fragmentación de conexiones en los dispositivos incluidos. No significa que todos los cargadores entreguen la misma potencia.'],['Antes de comprar','Revisa la potencia que necesita tu equipo y la que ofrece el adaptador. Un conector que encaja no garantiza que el ordenador cargue a la velocidad prevista. Conserva la documentación del fabricante para comprobar la compatibilidad.']],sources:[['Consejo de la Unión Europea','https://www.consilium.europa.eu/en/infographics/2022-06-07-common-charger-directive/']]},
 {slug:'etiqueta-energetica-moviles',category:'Consumo',type:'Guía',title:'La etiqueta del móvil que merece un minuto antes de comprar',summary:'Autonomía, resistencia y reparabilidad: cómo comparar más allá de la cámara y el precio.',minutes:4,sections:[['Una comparación más útil','Los requisitos europeos de etiquetado para teléfonos inteligentes y tabletas se aplican desde el 20 de junio de 2025 a los dispositivos que se introducen en el mercado y están dentro de su ámbito. La etiqueta ayuda a comparar eficiencia y otras características.'],['Dos escalas diferentes','La eficiencia energética se expresa de A a G. La clase de reparabilidad utiliza otra escala, de A a E. No confundas ambos indicadores: valoran aspectos distintos del producto.']],sources:[['Comisión Europea: smartphones y tabletas','https://energy-efficient-products.ec.europa.eu/product-list/smartphones-and-tablets_en']]},
 {slug:'windows-10-fin-soporte',category:'Tecnología',type:'Guía',title:'¿Sigues con Windows 10? Estas son tus opciones',summary:'El ordenador sigue encendiéndose, pero el soporte ordinario terminó. Qué revisar antes de decidir.',minutes:3,sections:[['El cambio que no se ve','El soporte ordinario de Windows 10 terminó el 14 de octubre de 2025. El sistema continúa funcionando, pero eso no equivale a seguir recibiendo las actualizaciones de seguridad del soporte normal.'],['Revisa las alternativas','Comprueba si tu ordenador cumple los requisitos de Windows 11. Microsoft también ofrece un programa de actualizaciones de seguridad extendidas para determinados equipos. Consulta las condiciones vigentes y su duración antes de tomar una decisión.']],sources:[['Microsoft: fin del soporte de Windows 10','https://support.microsoft.com/es-es/windows/deployment/updates-lifecycle/windows-10-support-has-ended-on-october-14-2025']]}
];
articles[0].sections.push(
 ['Una pequeña ficha para no equivocarte','Antes de ir a la tienda, apunta el modelo exacto del portátil, la potencia indicada en su adaptador y los requisitos de carga de su manual. Después compara esa ficha con la del cargador que quieres aprovechar. Si un adaptador tiene varias salidas, comprueba también qué ofrece cuando las usas a la vez. Es una comprobación más útil que fijarse solo en una cifra grande impresa en la caja.'],
 ['Lo que no conviene dar por hecho','La forma del conector no describe por sí sola todas las prestaciones del cable. No deduzcas la velocidad de transferencia, la salida de vídeo o la compatibilidad con una base únicamente porque todo sea USB-C. Busca la función que necesitas en las especificaciones de ambos extremos de la conexión.'],
 ['La decisión práctica','Si tu equipo funciona correctamente, esta noticia no es un motivo para sustituirlo. Haz primero inventario de los accesorios que tienes y etiqueta los que hayas comprobado. Guarda juntos el adaptador y el cable adecuados para tu portátil: así evitas volver a resolver la misma duda cuando preparas la mochila. Esta guía no incluye ensayos de cargadores ni recomienda un modelo concreto.']
);
articles[1].sections.push(
 ['Cómo llevarlo a una compra real','Escribe primero tus tres prioridades. Para alguien que viaja pueden ser batería, peso y facilidad de reparación; para quien trabaja con fotografías, almacenamiento, pantalla y soporte de sus aplicaciones. La etiqueta aporta información comparable, pero no sustituye estas necesidades ni es una puntuación global del teléfono.'],
 ['Haz una tabla de dos candidatos','Reserva una columna para cada modelo y anota precio final, autonomía declarada, reparabilidad y lo que incluye la caja. Añade una fila para aquello que no has podido verificar. Dejar una casilla como desconocida es preferible a convertir una promesa comercial en un dato. Comprueba que comparas la misma capacidad de almacenamiento y la misma variante.'],
 ['El coste que queda fuera del escaparate','Antes de decidir, calcula cuánto pagarías también por los accesorios que de verdad necesitas. Pregunta por el procedimiento de reparación y busca las condiciones de soporte del fabricante. No hay una elección universal: la utilidad de esta ficha está en hacer visibles tus prioridades. Prisma Diario no ha probado estos dispositivos; esta es una guía de lectura de información pública.']
);
articles[2].sections.push(
 ['Haz inventario antes de cambiar nada','Apunta el modelo del ordenador y las aplicaciones que necesitas a diario. Incluye impresora, escáner y otros periféricos importantes. Comprueba en sus páginas oficiales si funcionan en el sistema al que quieres pasar. Una actualización que deja fuera tu herramienta de trabajo no está bien planificada aunque el ordenador cumpla los requisitos generales.'],
 ['Separa tus archivos de tus programas','Prepara una copia de los documentos que no puedes perder y verifica que puedes abrirla desde otro lugar. Anota dónde están las licencias y cómo recuperarías el acceso a tus cuentas. Evita descubrir durante el cambio que el único método de recuperación dependía de ese mismo equipo.'],
 ['Elige con una lista, no con prisa','Compara actualizar el equipo compatible, acogerte temporalmente a una opción de soporte disponible o cambiar de equipo si lo necesitas. Escribe el coste, la duración del soporte y los pasos pendientes de cada alternativa. No utilices instaladores de procedencia desconocida para saltarte comprobaciones. Para equipos de empresa o ediciones especiales, consulta su ciclo de vida específico: esta guía se refiere al caso doméstico general.']
);
articles.push(
 {slug:'suscripciones-gasto-mensual',category:'Ahorro',type:'Método',title:'Las pequeñas cuotas también cuentan: pon orden a tus suscripciones',summary:'Un inventario de veinte minutos para ver qué pagas, qué utilizas y cuándo se renueva.',minutes:3,sections:[
 ['Empieza por lo que ya has pagado','Abre tus recibos y revisa un periodo que incluya tanto cuotas mensuales como anuales. Apunta servicio, importe, frecuencia y próxima renovación. Incluye almacenamiento, aplicaciones, entretenimiento y cualquier otro pago recurrente que reconozcas. No necesitas compartir el extracto ni conectar tu banco a ninguna herramienta: una tabla en tu ordenador sirve.'],
 ['Compara todas las cuotas en la misma unidad','Divide una cuota anual entre doce para expresarla como coste mensual equivalente. Por ejemplo, 60 € al año equivalen a 5 € al mes. No confundas esta equivalencia con una opción de pago mensual: el servicio puede cobrarte los 60 € de una vez. Suma las cuotas mensuales equivalentes para conocer el compromiso total.'],
 ['Un ejemplo, sin promesas de ahorro','Imagina tres servicios de 9 €, 6 € y 5 € mensuales. Juntos suman 20 € al mes y 240 € al año. Prescindir de uno de 6 € reduciría los pagos futuros en 72 € anuales si no hay penalización ni otros cargos y el precio permanece igual. Es una cuenta hipotética, no una estimación de lo que tú ahorrarás.'],
 ['Decide según el uso y revisa las condiciones','Anota cuándo utilizaste cada servicio por última vez y qué perderías al darlo de baja. Si guarda archivos, exporta lo importante y verifica la copia antes de cancelar. Comprueba si el cambio conserva el acceso hasta el final del periodo pagado y guarda la confirmación. Borrar una aplicación no demuestra que su suscripción haya terminado.'],
 ['Una revisión que puedas repetir','Elige una fecha mensual para actualizar la tabla. Si quieres probar un servicio nuevo, anota el coste tras la promoción y la fecha de renovación antes de contratar. Esta rutina no decide por ti qué merece la pena: te permite escoger con todas las cifras a la vista. Los ejemplos y el método de esta página son elaboración de Prisma Diario.']],sources:[]},
 {slug:'mensajes-falsos-phishing',category:'Seguridad',type:'Guía',title:'Ese mensaje urgente puede esperar: cómo comprobar un enlace sospechoso',summary:'Paquetes, supuestos bloqueos y premios: una rutina sencilla antes de entregar datos.',minutes:3,sections:[
 ['Primero, cambia de canal','El phishing intenta hacerse pasar por una organización legítima para obtener datos, dinero o acceso al dispositivo. INCIBE explica que puede utilizar enlaces o archivos fraudulentos. Si un mensaje te exige actuar deprisa, abre tú la aplicación oficial o escribe la dirección conocida de la entidad, sin utilizar el enlace del mensaje.'],
 ['Comprueba la petición completa','Piensa si esperabas esa comunicación y qué te está pidiendo. Un logotipo conocido o un texto bien redactado no bastan para demostrar su origen. Si hay una incidencia real, busca la información desde el canal que ya utilizabas antes de recibir el aviso. No respondas al remitente para comprobar si él mismo es legítimo.'],
 ['Un ejemplo de comprobación','Supón que recibes un aviso de un paquete pendiente y, precisamente, esperas una compra. Esa coincidencia puede hacerlo creíble, pero no verifica el mensaje. Entra por tu cuenta en la tienda donde compraste, localiza el pedido y consulta desde allí el seguimiento. La comprobación nace de una operación que conoces, no de los datos que proporciona el aviso.'],
 ['Si ya has introducido información','Deja de interactuar con la página y conserva las pruebas. Si facilitaste datos de una tarjeta, contacta cuanto antes con tu entidad por su canal oficial. Si compartiste una contraseña, cambia la de la cuenta afectada desde el servicio legítimo y revisa dónde la habías reutilizado. Busca orientación en los recursos de INCIBE.'],
 ['Haz que la próxima comprobación sea más fácil','Guarda de antemano los accesos oficiales de los servicios que utilizas con frecuencia. Comenta esta rutina con las personas a las que sueles ayudar con el móvil. El objetivo no es detectar todos los detalles de una falsificación, sino disponer de una forma independiente de verificar lo que te piden.']],sources:[['INCIBE: qué es el phishing','https://www.incibe.es/aprendeciberseguridad/phishing'],['INCIBE: ejemplo de suplantación de Correos','https://www.incibe.es/index.php/ciudadania/avisos/has-recibido-un-email-de-correos-guarda-precaucion-puede-ser-un-phishing']]},
 {slug:'copias-seguridad-3-2-1',category:'Seguridad',type:'Guía',title:'Tus fotos necesitan algo más que estar en el móvil',summary:'Qué significa la regla 3-2-1 y cómo empezar una copia de seguridad que puedas recuperar.',minutes:3,sections:[
 ['Tres, dos, uno','La estrategia 3-2-1 que recoge INCIBE propone conservar tres copias de la información importante, en dos soportes distintos, y una de ellas fuera de la ubicación principal. El original cuenta como una de las tres. La finalidad es reducir la dependencia de un único dispositivo o lugar.'],
 ['Empieza por una carpeta pequeña','Elige documentos o fotografías que realmente no puedas recuperar de otra manera. Organiza una primera copia en un soporte independiente y una segunda en otra ubicación adecuada. No hace falta resolver todos tus archivos el primer día. Empieza por un conjunto que puedas revisar de principio a fin y amplía después la rutina.'],
 ['La prueba que da sentido a la copia','Selecciona un archivo de prueba, recupéralo desde la copia en una carpeta diferente y ábrelo. Comprueba que es la versión que esperabas y que puedes localizarlo sin adivinar nombres. Anota la fecha de esta prueba. Ver un icono de sincronización o una carpeta con archivos no demuestra por sí solo que puedas restaurar lo que necesitas.'],
 ['Piensa en el día en que falle el dispositivo','Imagina que no tienes acceso al móvil o al ordenador principal. ¿Sabes dónde está la copia? ¿Puedes entrar en la cuenta que la guarda? ¿El método para recuperar esa cuenta depende exclusivamente del aparato perdido? Responder ahora a estas preguntas permite descubrir dependencias antes de que se conviertan en un problema.'],
 ['Mantén una rutina pequeña','Elige la frecuencia según lo que cambien tus archivos y cuánta información estarías dispuesto a perder. Tras una sesión importante de fotos o trabajo, comprueba la copia. Revisa también el espacio disponible y las condiciones del servicio que utilices. Este ejemplo organiza una rutina doméstica; no sustituye el diseño de un plan de continuidad para una empresa.']],sources:[['INCIBE: guía de copias de seguridad','https://www.incibe.es/sites/default/files/contenidos/guias/guia-copias-de-seguridad.pdf']]}
);
