import {mkdir,writeFile,readFile,copyFile} from 'node:fs/promises';
import {articles} from '../content/articles.mjs';
import config from '../site.config.mjs';
const origin=(process.env.SITE_URL||config.origin).replace(/\/$/,'');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const nav=['Tecnología','Consumo','Seguridad','Ahorro'];
const cats={'Tecnología':'tecnologia','Consumo':'consumo','Seguridad':'seguridad','Ahorro':'ahorro'};
const header=`<a class="skip" href="#contenido">Saltar al contenido</a><div class="topbar"><span>ESPAÑA · TECNOLOGÍA Y VIDA COTIDIANA</span><span>Edición · 20 septiembre 2026</span></div><header><a class="brand" href="/">prisma<span>diario.</span></a><span class="tagline">Entender lo que cambia.<br>Elegir un poco mejor.</span></header><nav aria-label="Navegación principal"><a href="/">Portada</a>${nav.map(n=>`<a href="/tema/${cats[n]}/">${n}</a>`).join('')}<a class="nav-about" href="/sobre-nosotros/">Nuestro criterio ↗</a></nav>`;
const footer=`<footer><a class="brand" href="/">prisma<span>diario.</span></a><p>Actualidad útil para tu vida digital.</p><div><a href="/sobre-nosotros/">Sobre el proyecto</a><a href="/contacto/">Contacto</a><a href="/privacidad/">Privacidad</a><a href="/aviso-legal/">Aviso legal</a><a href="/feed.xml">RSS</a></div><small>© 2026 Prisma Diario · ${esc(config.owner)}</small></footer>`;
function page(title,description,body,path='/',extra=''){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Prisma Diario</title><meta name="description" content="${esc(description)}">${origin?`<link rel="canonical" href="${origin}${path}">`:''}<meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta name="theme-color" content="#164e42"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='6' fill='%23164e42'/%3E%3Cpath d='M8 25V7h9a6 6 0 0 1 0 12h-4v6zm5-11h4a1 1 0 0 0 0-2h-4z' fill='white'/%3E%3C/svg%3E"><link rel="stylesheet" href="/style.css">${extra}</head><body>${header}<main id="contenido">${body}</main>${footer}</body></html>`;}
async function save(path,html){const dest=path==='/'?'dist/index.html':`dist${path}index.html`;await mkdir(dest.slice(0,dest.lastIndexOf('/')),{recursive:true});await writeFile(dest,html);}
const card=(a,i=0)=>`<article class="card"><div class="eyebrow">${esc(a.category)} <span> / ${esc(a.type)}</span></div><h3><a href="/articulo/${a.slug}/">${esc(a.title)}</a></h3><p>${esc(a.summary)}</p><div class="meta">20 SEP 2026 <span>· ${a.minutes} MIN DE LECTURA</span></div></article>`;
const hero=articles[0];
await mkdir('dist',{recursive:true});await copyFile('src/style.css','dist/style.css');
await save('/',page('Tecnología y actualidad útil','Noticias explicadas y guías sobre tecnología cotidiana, consumo, seguridad y ahorro digital.',`<div class="edition"><span>EL FOCO</span><span>Noticias con contexto. Guías que sirven.</span></div><section class="hero"><article><div class="eyebrow">TECNOLOGÍA <span>/ A FONDO</span></div><h1><a href="/articulo/${hero.slug}/">${hero.title}</a></h1><p class="standfirst">${hero.summary}</p><a class="read" href="/articulo/${hero.slug}/">Entender el cambio <span>↗</span></a><div class="meta">20 SEP 2026 · ${hero.minutes} MIN DE LECTURA</div></article><div class="hero-visual"><div class="visual-label">EL CARGADOR COMÚN</div><div class="big-type">Un puerto.<br>Más posibilidades.</div><div class="visual-bottom"><span>USB-C</span><span>28.04.2026<br>PORTÁTILES EN LA UE</span></div></div></section><section class="latest"><div class="section-head"><h2>Lo que conviene saber</h2><span>LECTURAS SELECCIONADAS</span></div><div class="grid">${articles.slice(1).map(card).join('')}</div></section><aside class="editorial"><span class="eyebrow">EL CRITERIO PRISMA</span><h2>Menos ruido.<br>Más contexto.</h2><p>Explicamos qué cambia, a quién afecta y qué puedes hacer. Con fuentes que puedes consultar y sin titulares de urgencia inventados.</p><a href="/sobre-nosotros/">Así elaboramos las guías ↗</a></aside>`));
for(const a of articles){const path=`/articulo/${a.slug}/`;await save(path,page(a.title,a.summary,`<div class="breadcrumb"><a href="/">Portada</a> / <a href="/tema/${cats[a.category]}/">${a.category}</a></div><article class="article"><div class="eyebrow">${a.category} / ${a.type}</div><h1>${a.title}</h1><p class="standfirst">${a.summary}</p><p class="byline">Prisma Diario · Publicado el 20 de septiembre de 2026 · ${a.minutes} min</p><div class="article-body">${a.sections.map(([h,p])=>`<h2>${h}</h2><p>${p}</p>`).join('')}<aside class="sources"><h2>Consulta las fuentes</h2><ul>${a.sources.map(([t,u])=>`<li><a href="${esc(u)}" rel="noreferrer">${esc(t)} ↗</a></li>`).join('')}</ul><p>Fuentes consultadas el 20 de septiembre de 2026. Comprueba las condiciones actuales en la fuente oficial antes de actuar.</p></aside></div></article><section class="latest"><div class="section-head"><h2>Para seguir leyendo</h2></div><div class="grid">${articles.filter(b=>b!==a).slice(0,3).map(card).join('')}</div></section>`,path));}
for(const n of nav){const list=articles.filter(a=>a.category===n);await save(`/tema/${cats[n]}/`,page(n,`Guías y actualidad sobre ${n.toLowerCase()}.`,`<section class="category"><div class="eyebrow">EXPLORA PRISMA</div><h1>${n}</h1><div class="grid">${list.length?list.map(card).join(''):'<p>Estamos preparando las primeras guías de esta sección.</p>'}</div></section>`));}
for(const [slug,title,body] of [
 ['sobre-nosotros','Nuestro criterio','<p>Prisma Diario es un proyecto editorial independiente sobre tecnología cotidiana, consumo y ahorro digital. Seleccionamos temas por su utilidad para los lectores en España.</p><h2>Cómo se elabora el contenido</h2><p>Esta primera edición se ha preparado con asistencia de inteligencia artificial a partir de documentación pública. Cada artículo identifica las fuentes consultadas. No presentamos estas guías como pruebas de producto ni como reportajes presenciales.</p><h2>Fechas y correcciones</h2><p>Distinguimos la fecha de publicación de cada guía de la fecha del hecho que explica. La web no se actualiza automáticamente. El canal público de correcciones se habilitará cuando se complete la identificación del titular.</p>'],
 ['privacidad','Privacidad y cookies','<p>Esta versión no incorpora publicidad, formularios, analítica de audiencia ni cookies instaladas por Prisma Diario. El proveedor de alojamiento puede tratar datos técnicos necesarios para servir y proteger la web.</p><h2>Enlaces externos</h2><p>Las fuentes enlazadas tienen sus propias políticas. Los datos que facilites en esas páginas se rigen por las condiciones de sus respectivos titulares.</p><h2>Antes de activar publicidad</h2><p>Se actualizará esta información con el responsable, los proveedores y el tratamiento aplicable, y se configurará la gestión del consentimiento correspondiente.</p>'],
 ['aviso-legal','Información del proyecto','<p>Prisma Diario se encuentra en fase de preparación editorial. La identificación completa del titular y el correo de contacto público están pendientes de incorporación. Esta página no constituye todavía un aviso legal completo para una actividad comercial.</p><p>El contenido tiene finalidad informativa general. Las condiciones de productos y servicios pueden cambiar; consulta siempre la documentación oficial enlazada.</p>']
])await save(`/${slug}/`,page(title,title,`<article class="article legal"><h1>${title}</h1><div class="article-body">${body}</div></article>`,`/${slug}/`));
console.log(`Generadas portada, ${articles.length} artículos, ${nav.length} categorías y páginas editoriales.`);
await import('./finish-build.mjs');
