import {mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {articles} from '../content/articles.mjs';
import config from '../site.config.mjs';
const out='blogger';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
const date='2026-09-20T10:00:00+02:00';
const entries=[];
await mkdir(`${out}/html`,{recursive:true});
function entry(slug,title,html,kind,labels=[]){
 const uid=createHash('sha256').update('prisma-diario-migration:'+kind+':'+slug).digest('hex');
 entries.push(`<entry><id>urn:prisma-diario:${uid}</id><published>${date}</published><updated>${date}</updated><category scheme="http://schemas.google.com/g/2005#kind" term="http://schemas.google.com/blogger/2008/kind#${kind}"/>${labels.map(l=>`<category scheme="http://www.blogger.com/atom/ns#" term="${esc(l)}"/>`).join('')}<title type="text">${esc(title)}</title><content type="html">${esc(html)}</content><author><name>Prisma Diario</name></author><app:control><app:draft>yes</app:draft></app:control></entry>`);
 return writeFile(`${out}/html/${slug}.html`,html);
}
for(const a of articles){
 const html=`<p class="prisma-summary">${esc(a.summary)}</p><!--more--><p><small>Publicado originalmente en Prisma Diario el 20 de septiembre de 2026. Fuentes consultadas en esa fecha.</small></p>${a.sections.map(([h,p])=>`<h2>${esc(h)}</h2><p>${esc(p)}</p>`).join('')}<hr/><h2>${a.sources.length?'Fuentes':'Sobre este método'}</h2>${a.sources.length?`<ul>${a.sources.map(([t,u])=>`<li><a href="${esc(u)}" rel="noreferrer">${esc(t)}</a></li>`).join('')}</ul>`:'<p>Elaboración de Prisma Diario. Los importes son ejemplos aritméticos hipotéticos, no precios ni promesas de ahorro.</p>'}<p>Las condiciones pueden cambiar. Consulta la fuente oficial antes de actuar.</p><p>Correcciones: <a href="mailto:${esc(config.email)}">${esc(config.email)}</a>.</p>`;
 await entry(a.slug,a.title,html,'post',[a.category]);
}
const pages=[
 ['sobre-prisma','Sobre Prisma Diario',`<p>Prisma Diario es un proyecto editorial sobre tecnología cotidiana, consumo, seguridad y ahorro digital dirigido a lectores en España.</p><h2>Responsable</h2><p>${esc(config.owner)}. Contacto: <a href="mailto:${esc(config.email)}">${esc(config.email)}</a>.</p><h2>Criterio editorial</h2><p>Esta primera edición se ha elaborado con asistencia de inteligencia artificial a partir de fuentes públicas citadas en cada guía. No presentamos los textos como pruebas de producto ni reportajes presenciales.</p><p>Comprobamos las fuentes y distinguimos las fechas de los hechos de las fechas de publicación. La frecuencia editorial prevista es de dos artículos y una actualización por semana; no es un servicio de noticias en tiempo real.</p><h2>Correcciones</h2><p>Si encuentras un error, escribe indicando artículo, dato y fuente. Los cambios relevantes se identificarán en la publicación.</p>`],
 ['contacto','Contacto y correcciones',`<p>Responsable: ${esc(config.owner)}.</p><p>Escribe a <a href="mailto:${esc(config.email)}">${esc(config.email)}</a> para consultas y correcciones. Incluye el título del artículo y el dato que deseas revisar.</p><p>Evita enviar contraseñas, documentos de identidad o información bancaria. No hay formularios de suscripción ni un boletín activo.</p>`],
 ['privacidad','Privacidad y cookies',`<p>Responsable editorial: ${esc(config.owner)}. Contacto: <a href="mailto:${esc(config.email)}">${esc(config.email)}</a>.</p><h2>Alojamiento y servicios de Google</h2><p>Este blog utiliza Blogger, un servicio de Google. Google puede tratar información técnica y utilizar cookies relacionadas con la prestación del servicio. Consulta su <a href="https://policies.google.com/privacy?hl=es">política de privacidad</a> y su <a href="https://policies.google.com/technologies/cookies?hl=es">información sobre cookies</a>.</p><h2>Contacto por correo</h2><p>Si escribes al correo de contacto, se reciben tu dirección y el contenido del mensaje para atender tu consulta. No envíes información sensible que no sea necesaria. El correo se gestiona mediante Gmail.</p><h2>Publicidad</h2><p>Prisma Diario no ha activado anuncios ni añadido Google Analytics a esta versión. Antes de activar AdSense se revisará la información sobre proveedores y consentimiento aplicable.</p><h2>Información pendiente</h2><p>Este texto es provisional. Debe completarse la información legal correspondiente al responsable y al tratamiento efectivo antes de iniciar la monetización.</p>`],
 ['aviso-legal','Información del titular',`<p>Titular: ${esc(config.owner)}.</p><p>Contacto: <a href="mailto:${esc(config.email)}">${esc(config.email)}</a>.</p><p>Proyecto editorial informativo. Los datos legales adicionales que correspondan a la actividad están pendientes de completar; esta página no constituye todavía un aviso legal completo para una actividad comercial.</p><p>Las guías no sustituyen la documentación oficial de los productos y servicios. No existe una garantía de ahorro ni de resultados individuales.</p>`]
];
for(const [slug,title,html] of pages)await entry(slug,title,html,'page');
await writeFile(`${out}/prisma-diario-import.xml`,`<?xml version="1.0" encoding="UTF-8"?>\n<feed xmlns="http://www.w3.org/2005/Atom" xmlns:app="http://purl.org/atom/app#"><id>urn:prisma-diario:migration:2026-09</id><updated>${date}</updated><title type="text">Prisma Diario</title><generator version="1.0">Prisma Diario migration exporter</generator>${entries.join('\n')}</feed>`);
console.log(`Exportados ${articles.length} artículos y ${pages.length} páginas como borradores. Importación real pendiente de validar en Blogger.`);
